## Nome do workflow que aparecerá na aba "Actions" do GitHub
name: Deploy static content to Pages

on:
  # Executa automaticamente quando houver um push na branch "master"
  push:
    branches: ["master"]

  # Permite executar o workflow manualmente pela aba "Actions" do GitHub
  workflow_dispatch:

# Permissões
permissions:
  contents: read
  pages: write
  id-token: write

# Controle de execuções simultâneas
concurrency:
  # Define um grupo para os deploys do Pages
  group: "pages"

  # Não cancela um deploy que já começou
  cancel-in-progress: false

  # Jobs
jobs:
  # Job responsável pelo deploy
  deploy:
    # Ambiente utilizado pelo GitHub Pages
    environment:
      name: github-pages

      # Depois que o deploy terminar,
      # o GitHub fornece a URL da página
      url:
        ${{ steps.deployment.outputs.page_url }}

        # Máquina virtual onde o workflow será executado
    runs-on:
      ubuntu-latest

      # Etapas do deploy
    steps:
      # 1. Baixa o conteúdo do repositório
      - name: Checkout
        uses: actions/checkout@v4

      # 2. Configura o ambiente do GitHub Pages
      - name: Setup Pages
        uses:
          actions/configure-pages@v5

          # 3. Cria o artefato que será publicado
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Envia todo o conteúdo do repositório
          path:
            "."

            # 4. Publica o artefato no GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
